import '../styles/main.scss'
import { Goldman, Titillium_Web } from 'next/font/google'


const goldman = Goldman({
  subsets: ['latin'],
  variable: "--font-goldman",
  weight: '400'
})
const titillium_Web = Titillium_Web({
  weight: "300",
  style: "normal",
  display: "swap",
  subsets: ['latin'],
  variable: "--font-titillium-web"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${goldman.variable} ${titillium_Web.variable}`}>{children}</body>
    </html>
  )
}
